//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProactiveBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public System.DateTime TokenRaised { get; set; }
        public string Issue_Details { get; set; }
        public string ServerName { get; set; }
        public string MiddlewareService { get; set; }
        public string DatbaseName { get; set; }
    }
}
